### ISSUE TITLE
Issue while laying tracks

### ISSUE THREAD

**Issue by nalilord** [Nexela/Nanobots#1]
Hey,

seems to be an interesting mod, but it crashed our server when is was using my T junction rail blueprint:

`1527.125 Error MainLoop.cpp:788: Exception at tick 22335660: Error while running event on_tick (ID 0)
Unknown item name: straight-rail
stack traceback:
	__Nanobots__/control.lua:68: in function 'build_ghosts_in_player_range'
	__Nanobots__/control.lua:129: in function <__Nanobots__/control.lua:121>
1527.126 Error ServerMultiplayerManager.cpp:93: MultiplayerManager failed: "Error while running event on_tick (ID 0)
Unknown item name: straight-rail
stack traceback:
	__Nanobots__/control.lua:68: in function 'build_ghosts_in_player_range'
	__Nanobots__/control.lua:129: in function <__Nanobots__/control.lua:121>"
1527.126 Info ServerMultiplayerManager.cpp:658: mapTick(22335660) changing state from(InGame) to(Failed)`

**Comment by Nexela** [comment]
Thanks for the report, A fix will be up shortly.
