### ISSUE TITLE
Script Error when upgrading Bob's Inserters with Nanobots

### ISSUE THREAD

**Issue by Nipahu** [Nexela/Nanobots#101]
When an upgrade planner is used to upgrade Bob's yellow to red inserters the Nanobot script reports the following error: https://imgur.com/R7vXHal

**Comment by mnoreke** [comment]
This is probably related to [https://github.com/Nexela/Nanobots/issues/95](url)

**Comment by pocghamp** [comment]
Had the same issue with Express inserters (still same error, says red inserter). It did upgrade a couple of them but not all. When placing the blueprint directly with express inserters there is no problem.

**Comment by Nexela** [comment]
Duplicate of #95
