### ISSUE TITLE
on_robot_built_entity not firing?

### ISSUE THREAD

**Issue by blargh2015** [Nexela/Nanobots#108]
In tinkering with another mod (Utilization Monitor Blargh), it seems like Nanobots-built objects do not trigger on_robot_built_entity. I get an on_built_entity for the ghost going down, but never the on_robot_built_entity firing.

It looks like another mod had a similar issue (talked about here https://mods.factorio.com/mod/early_construction/discussion/5c9699f4854c25000d4e0e86 with the resulting git patch at https://github.com/Aidiakapi/early_construction/commit/2270c359cf5b8277ee0d4727ca36d4ece6c9a08a) that it seems to be because the robots are destroyed immediately so Factorio doesn't send the on_robot_built_entity event. That patch in the other mod queues robot destruction for one tick, which reported fixes the problem.

Is nanobots subject to the same thing, and could the same fix be applied?

**Comment by Nexela** [comment]
I think all of the nanobots events have been switched over to use the script_raised variants

**Comment by blargh2015** [comment]
Ah, I (somehow) had missed that.  I updated my mod to catch the script_raised variants, and things are working now.  Thanks!
