### ISSUE TITLE
3.2.8 causes short freezes with Factorio 1.0.0

### ISSUE THREAD

**Issue by module0x90** [Nexela/Nanobots#109]
Hi,

I noticed that my game is freezing for 2-4 seconds every 80s. I enabled show-time-usage and it shows for
mod-Nanobots 0.2 / 0.024 / 2969.001 for example. The third number is occasionally sky-high, ie. >100.
If I disable this mod my game runs smoothly. There are occasional very short hiccups as well, like a split second,
and they also disappear when disabling this mod.
Every 80s or so the third number is like >2000.

Can you advise please which other information you require?
I just loaded the same game with Factorio 0.17.79 and Nanobots 3.1.0 and there are also hiccups, the last number on show-time-usage was just 90, but I didn't let it run for long.

Testing... I unequipped now the Nano emitter... same thing.
Now... I had in my 316k solarpanels, 3.8k roboports "tree marking" and "item pickup" enabled... and now the big spike is gone.

Thank you for this great mod...

Regards

Tom

**Comment by Nexela** [comment]
The best way to diagnose where the slowdown is coming from would be to have a copy of the save file I can play with.

**Comment by module0x90** [comment]
Hi,

thanks for coming back.
I did figure out end in the end from where it was coming from:
	I had in my 316k solarpanels, 3.8k roboports "tree marking" and "item pickup" enabled... and now the big spike is gone.
All good when I removed "tree marking" and "item pickup" on this network in particular.
Regards

Tom

August 30, 2020 5:01 AM, "Nicholas Dunn" <notifications@github.com (mailto:notifications@github.com?to=%22Nicholas%20Dunn%22%20<notifications@github.com>)> wrote:
	The best way to diagnose where the slowdown is coming from would be to have a copy of the save file I can play with.

**Comment by Nexela** [comment]
I'll will try and spend some time optimizing those areas a little bit.
