### ISSUE TITLE
Missing Vanilla Mechanic

### ISSUE THREAD

**Issue by SGZ-Creations** [Nexela/Nanobots#129]
#### Describe the Bug

When trying to use the vanilla funtion to rotate belts it conmsumes the nano bot(s) without doing any progress 

#### To Reproduce
1 craft nonobot emiter 
2 craft the nano bot
3 Make sure it's active before trying to rotate same level belt using the "shift + mb" placable mecanic

#### Save file & Username

Works on any old/new save using version 3.2.16 of this mod
and that u play in verion 1.1 or later

#### Log file

Nothing being loged in any vewieble way. knowingly

**Comment by Nexela** [comment]
I can't reproduce this. Any chance you could post a video

**Comment by Nexela** [comment]
Ahhh Figured it out, Thank you!

**Comment by SGZ-Creations** [comment]
> I can't reproduce this. Any chance you could post a video

could have have i noticed the post. sorry for that.
