### ISSUE TITLE
Constructors do not use item health

### ISSUE THREAD

**Issue by articulating** [Nexela/Nanobots#21]
I assume this breaks compatibility with Factorissimo, also means that players can get free repairs.

**Comment by Nexela** [comment]
Yes it would break Factorissimo.

Logic would need to be adjusted in queue_ghosts_in_range and in get_all_items_inside

**Comment by Nexela** [comment]
Replace this with something meaningful like... "@piascikj started working this issue."

----

TODO gh:21 using get_contents it is not possible to get the health. id:8
[**control.lua:95**](https://github.com/Nexela/Nanobots/blob/develop/control.lua#L95)

@imdone *comment-bot*. Get TODOBOTs to do your work at [imdone.io](https://imdone.io)

**Comment by Nexela** [comment]
Replace this with something meaningful like... "@piascikj started working this issue."

----

TODO using get_contents it is not possible to get the health. gh:21 id:9
[**control.lua:95**](https://github.com/Nexela/Nanobots/blob/develop/control.lua#L95)

@imdone *comment-bot*. Get TODOBOTs to do your work at [imdone.io](https://imdone.io)

**Comment by Nexela** [comment]
Replace this with something meaningful like... "@piascikj started working this issue."

----

TODO using get_contents it is not possible to get the health. id:9 gh:21
[**control.lua:95**](https://github.com/Nexela/Nanobots/blob/develop/control.lua#L95)

@imdone *comment-bot*. Get TODOBOTs to do your work at [imdone.io](https://imdone.io)
