### ISSUE TITLE
Sound entities not being removed causing chunks to stay active

### ISSUE THREAD

**Issue by Danielv123** [Nexela/Nanobots#26]
As mentioned on reddit, people have been having issues with this mod.

Submitting issue on behalf of everyone in this post with problems who haven't submitted an issue yet.

https://www.reddit.com/r/factorio/comments/5urmso/factorio_taking_all_16gb_of_my_ram_and_running/

**Comment by Nexela** [comment]
More infos and theories
https://www.reddit.com/r/factorio/comments/5urmso/factorio_taking_all_16gb_of_my_ram_and_running/ddwvncu/
