### ISSUE TITLE
"An area of zero size is not supported..."

### ISSUE THREAD

**Issue by ChristianNilaus** [Nexela/Nanobots#32]
Hi Nexela

I just upgraded to the latest version in the Mod portal (the Scrapper and Deconstruction Nanobots disappeared).
After that upgrade i have experienced this error a couple of times:
http://i.imgur.com/4jq4U1V.png

This may be an interaction between your mod and AAI Programmable Vehicles. I am driving in my car with the Construction Bots active, then I follow my automated squad of Chaingunners (AAI Mod) around in order to see that it works and add some repair. The AAI vehicles "self'repair" when they bump into each other, which may be the cause of this. I suppose it could be related to the nanobot trying to deploy and then it is not needed anyway, which causes the error.

I can give you a save game if you like, but I am running 60+ mods so it could be a hassle to recreate it for you. Otherwise try contacting me on Arumbas Discord (i lurk there a lot)

Great mod by the way :)

**Comment by Nexela** [comment]
I am pretty sure your diagnoses is spot on.  I will be able to test tonight.  and should be on track for an updated version if I can finish the shield code.
