### ISSUE TITLE
minor strangeness with latest update

### ISSUE THREAD

**Issue by DaveInTexas** [Nexela/Nanobots#39]
latest update converted all of my existing construction ammo to termite ammo. lol

**Comment by Nexela** [comment]
The latest version(s) remove the deconstructor/scrapper ammos and replaces them with constructors that can also deconstruct (and return items).  

There shouldn't be anything that changes construction ammo.  I will take a look tonight.  Do you happen to have the before and/or after save files?

**Comment by Nexela** [comment]
Further input needed
