### ISSUE TITLE
Nanobots don't place electric miners with modules 

### ISSUE THREAD

**Issue by wollfxp** [Nexela/Nanobots#42]
I tried building this blueprint `0eNq1ld1qhDAQhd9lriMkbrStr1Jk8Wd2CcQoMS4Vybs3UdpeKGikXkkS882ZM3KcoJQDdlooA9kEompVD9nnBL14qkL6PTN2CBkIgw0QUEXjVyixMlpUUSOUUM+o1kJKsASEqvELMmZzAqiMMAIX4LwY72poStTuhR0Uga7t3e1WeQ2OGMUERve4uSK10O7OfOZ2vbKlxqzRER8Pf/xy9aKmrQeJDle1g+/xZnNLVmriXzVGF6rvWm2iEqVZy6CbKvgG8xbK5PtMHuratmnpv5iWnBwhvWKCaajbbN/tt1BmvM98PzdBesUAPwL7O2AZo4FMeoB5NisuiQoWmhUHooKFZsWBD42dzIpLooIlgQ2usjAnP9X/flgEXqj7RSbnMU85TVhs7TeFyUzR`
with Nanobots. Electric miners disappeared, nothing happened and there's a Lua error in the console output.
Steps to reproduce:
1. create a blueprint containing electric miners with modules
2. place it anywhere
3. watch your miners disappear from the inventory and observe the error `__Nanobots__/control.lua:339: attempt to index local 'module_stack' (a number value)`

Blueprinted modules inside the chemical plants, assemblers and other entities work as expected.
Second time I tried reproducing this issue my miners stayed in the inventory.
I'm also attaching the screenshot, just in case.
![20170427221340_1](https://cloud.githubusercontent.com/assets/6288958/25500516/fe0831d0-2b97-11e7-9bdf-770a75aaa995.jpg)

Factorio 0.15.2, Nanobots 1.7.7.

**Comment by Nexela** [comment]
Thanks for the report.  I need to upgrade this part to account for the item-request-proxy changes.
