### ISSUE TITLE
Nanobot Queue recheck when placing

### ISSUE THREAD

**Issue by TokMor** [Nexela/Nanobots#44]
Certain conditions don't appear to be re-checked when placing an item from the queue. Not 100% positive if this is intended behavior or not.

If I turn off my roboport to get a bunch of stuff into the queue, I can turn my roboport back on (without a logistic interface chip equipped) and nanobots continue to place the queued items.

**Comment by Nexela** [comment]
This is intended behaviour, Once the ammo is drained the item is queued up for placement. Logitistic networks just disable the drain/add to queue portions
