### ISSUE TITLE
Severe UPS/FPS drop when standing near Steam engines

### ISSUE THREAD

**Issue by staviq** [Nexela/Nanobots#47]
I have isolated this issue down to Nanobots mod. ( I disabled all my mods, and the enabled one by one, only one at the time )

I had this weird issue where i get 60 fps/ups all the time, but when i pass near the power area (about 60 steam engines) the game freezes completely for about half a second every second, and the "Script update" counter goes up to 30-40 from 0.5 when i'm not around the steam engines.

**Comment by staviq** [comment]
I have verified that it only happens when i have Nano emitter equipped and selected. Deselecting it as a weapon ( i.e. switching to submachine gun ) does "fix" this issue.

**Comment by Nexela** [comment]
Thank you for the report. This will help me narrow down the issue.  
I am pretty sure it is related to the *smoke* from the steam engines.  If you want to try something replace
line 582 Control.lua
with 
```lua
for _, ghost in pairs(player.surface.find_entities_filtered{area=area, force=player.force}) do
```

Not sure why I don't have a force check and will need to investigate further!

**Comment by Nexela** [comment]
Well now I remember why It doens't have the force check.  Trees/entities don't have a force and won't turn up in searches ....

**Comment by Nexela** [comment]
Ok not checking for force is related to deconstruction.   trees/rocks don't have a force!

**Comment by Nexela** [comment]
Should have much better results in the next version. It is not perfect but I have put in an API request.
https://forums.factorio.com/viewtopic.php?f=28&t=45658&p=262662#p262662
