### ISSUE TITLE
Possible conflict with the Resource Spawner Overhaul mod.

### ISSUE THREAD

**Issue by staviq** [Nexela/Nanobots#50]
Hi, it's me again, sorry to bring you the bad news, i love your mod, but it seems like Nanobots screws up the ore patch generation in RSO, which is quite popular mod.

Long story short, it seems like having RSO and Nanobots mods, causes ore patches to be generated way to small to be usable.

You can read more about the problem in this thread, and specifically in this post ( I don't thing the original problem in this thread is related to Nanobots, so just skip to my posts in this thread ):

https://forums.factorio.com/viewtopic.php?p=264985#p264985

**Comment by Nexela** [comment]
I can't think of anything in Nanobots that could cause this.

I have some debug scripts that disable RSO all together but those only get run during world creation and you would know if they did :)

Can you check config.lua and let me know if DEBUG is false?

**Comment by staviq** [comment]
It is set to false.

**Comment by staviq** [comment]
Unequipping Nano emitter, and unlearning the research does not fix the problem

**Comment by Nexela** [comment]
I will look into this tonight and see if I can find anything that might be causing this.  Does this happen with just nanobots and rso installed?

**Comment by staviq** [comment]
I will test this with just the rso and nanobots without any other mods and let you know.

**Comment by staviq** [comment]
Problem still occurs with only rso and nanobots mods.
Disabling nanobots and leaving only rso fixes this issue.

**Comment by Nexela** [comment]
Can you try it with RSO and Picker Extended?  I am wondering if it might be something to do with the new settings options messing up the seed.

**Comment by staviq** [comment]
You are right about picker extended also causing this issue.

It seems however, that this problem is not entirely deterministic.

The simple testing procedure is to load the "15_7" game save ( https://www.dropbox.com/s/ooc5ntw81639t7h/15_7.zip?dl=0 ), then enable god mode ( /c game.player.character = nil ), then zoom out for faster travel, then go directly left, to the edge of discovered map, and then some to discover more map and force ore patch generation. Before the big water, there should be large copper ore path, just on the top of the screen if you only press left from where you start in the game save, about . If you get to the water and there is no large ore patch, ore patch generation is not working propertly, if you do it is working propertly ( 
at least better than when it is not, because at this point i'm not sure what the "proper" generation is, but the ore patches should be "very large" )

I have done this procedure, with, rso and nanobots, with rso and picker extended, and with rso only, about 50 times.

1. Results for the same actions are not always the same, about 5% of the time, ore generation would not work when only rso is enabled, but always, restarting the game and repeating the procedure exactly the same way would cause it to work propertly again.

2. I have noticed only once, that biter bases and ore patches were generated completly diffrently than in other cases.

3. The 5% of undeterministic results were happening after several game quit/ load game cycles, never on fresh factorio start

4. In general, it makes no difference which of two, nanobots or picker extended are enabled, but it makes a significant difference if they are enabled or not.

5. If the rare case of ore generation not working with only rso enabled and other mods disabled happens, it will not help to quit game and load the game save again, you need to quit factorio and restart it in order to make it work ( just restart, without enabling or disabling any mods ).
Because of that, it seems to me, like this might be a bug in factorio itself, and it's handling of mod settings.

**Comment by staviq** [comment]
6. I'm unable to recreate this issue on newly started maps, so either it's connected to this particular game save, or it only happens far away from the starting zone.

**Comment by Nexela** [comment]
Thanks for tests and load of information. I will give it a few shots and see if I can reproduce it.  However I have a feeling it is a Factorio issue at this point also.  I have a few pre-.15 maps I will give it a try on when I get a chance.

**Comment by staviq** [comment]
I just want to let you know, i have managed to reproduce this problem with Nanobots disabled, so at this point, even though enabling or disabling Nanoobots do most of the time change the state of the problem, it's more than likely this problem is in factorio itself, and Orzelek did report this to the devs.

More details in the same forum thread i linked at the beginning.

**Comment by Nexela** [comment]
Found Orzelek's post and it is indeed a Factorio bug/desync fixed in the next version.
Thank you again for all of your hard work and testing to narrow this down!
