### ISSUE TITLE
Not working - Gun loaded, Bots loaded, not doing anything

### ISSUE THREAD

**Issue by NetTecture** [Nexela/Nanobots#52]
Save attached. 

[TTO.zip](https://github.com/Nexela/Nanobots/files/980153/TTO.zip)

RIght there, the player. With an emitter selected. Nothing happens. Looks like an event not firing.

**Comment by Nexela** [comment]
Thank you for the report, However termite bots ignore trees marked for deconstruction.   Moving into the unmarked patch of trees causes the termites to fire at those.

Switch over to the constructor bots to mine trees marked for deconstruction.
