### ISSUE TITLE
Nanobots ignoring inserter blueprint settings from Bob's.

### ISSUE THREAD

**Issue by rhyser9** [Nexela/Nanobots#53]
I'm having a problem where whenever I place a blueprint of an adjusted inserter from Bob's (different pickup/dropoff/offset), the blueprint ghost shows the correct settings, but when the item is actually placed, the inserter reverts back to default settings. This doesn't occur with construction robots, only nanobots, and seems to be save specific as well. I generated a new world to test it, and nanobots place the inserters just fine there, but not on my actual play world. Let me know what else you need. Any suggestions?

**Comment by Nexela** [comment]
Check your bob logistic inserter settings and make sure you don't have the overrides enabled.

**Comment by rhyser9** [comment]
"Enable positions overrides" is unchecked

**Comment by Nexela** [comment]
Can you post your save/modpack on google drive/dropbox

**Comment by rhyser9** [comment]
Okay, I was messing around for a sec, and it is the Bob's inserter pad. It either position overrides or the GUI mode are enabled, it overrides the inserter placement, but it works fine if both are unchecked. I'd never noticed because I don't use the menu via the inserter button, just the hotkeys for the GUI. So it's not nanobots after all, whoops!

**Comment by rhyser9** [comment]
Wait, or is it? Because it doesn't seem to happen with construction robots still, regardless of whether GUI mod or position overrides is enabled.

**Comment by Nexela** [comment]
Construction robots use on_robot_built, Nanobots use on_built  (player built)

**Comment by rhyser9** [comment]
So I guess going forward just make sure that GUI mode is disabled? I guess that's easy enough!
Here's save/modpack if you want it: https://drive.google.com/open?id=0B7L8j51ie4jASlFjZ3A5RlExZHM

**Comment by ritobanrc** [comment]
I'm still having this problem and can't find where the position overrides or GUI mode checkboxes are. Help?
