### ISSUE TITLE
Nanobots broken in version 0.15.14

### ISSUE THREAD

**Issue by jforr** [Nexela/Nanobots#54]
I'm not expert enough to say why, but I get a repeatable crash anytime I place a ghost down and wait for nanobots to build.

**Comment by Nexela** [comment]
Factorio is broken in 0.15.14

Waiting for an official dev response before making any changes.

**Comment by DaveSharman** [comment]
You also get the same crash when sending out the termite nanobots to clear trees.  But I expect this is the same issue as above.

**Comment by DaveSharman** [comment]
BTW, they should totally incorporate this into the base game.  This mod is simply AWESOME!!!

**Comment by Nexela** [comment]
Thanks I totally agree, And yes related. Will be fixed in the next Factorio release.

**Comment by DaveSharman** [comment]
Confirmed to be working as intended in 15.15.  It no longer crashes.
