### ISSUE TITLE
Running Make

### ISSUE THREAD

**Issue by CynicalTaco** [Nexela/Nanobots#56]
Three issues I ran into while setting up. 

Trying to build from any of the releases packages will not work as they do not have the git files so they can't use git tag to pull the version; not a big deal since you would really only ever clone the repo. I obviously just put it manually but something to consider.

Trying to build at all fails on the check stage even though luacheck doesn't return any hard errors just warnings. You can add the -q or --quiet parameter to  luacheck to fix this issue.

When building myself I discovered the print statement for tickrate was not commented out on controls.lua

**Comment by Nexela** [comment]
The makefile is only meant for building a release as it removed any files not needed. The luacheck fail is deliberate. If it doesn't pass I don't want to do a release :)

As for the tickrate, I only update master after doing a release, It seems I forgot to push my changes.  I am used to the makefile I have for picker which automates pushing the changes.

**Comment by CynicalTaco** [comment]
The luacheck -q parameter only removes warnings, which are harmless, not errors so that shouldn't be an issue at all and won't let you push a failed project. 
https://luacheck.readthedocs.io/en/stable/cli.html#command-line-options

Just figured I would let you know and thanks for all the work on your awesome mods.

**Comment by Nexela** [comment]
Thank you!

In my opinion a warning is just as bad as a fail :)

**Comment by CynicalTaco** [comment]
I completely understand, and thanks I will grab the config you use.
