### ISSUE TITLE
Intermittent error when near train tracks

### ISSUE THREAD

**Issue by sgtsquiggs** [Nexela/Nanobots#57]
Occurs when I have the Nano Emitter equipped and I'm in a car near train tracks:

`Nanobots/control.lua:99: attempt to index field 'train'(a nil value)`

Happens once a second or so. Driving away from the train track stops it. I can't find any debugging logs, are there any I can enable to help?

**Comment by sgtsquiggs** [comment]
Actually it was happening to me just now and I was not near any tracks: 

[Screenshot](https://steamuserimages-a.akamaihd.net/ugc/854974796525669696/CDD6C7BF2AA001406420390D3DF7A6E24E6ADB85/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|2048:1152&composite-to%3D%2A%2C%2A%7C2048%3A1152&background-color=black)

**Comment by Nexela** [comment]
I will get a fix pushed out tonight.
