### ISSUE TITLE
Attempt to index nil value error in control.lua

### ISSUE THREAD

**Issue by eblume** [Nexela/Nanobots#58]
Hi there,

Mid-game I got four or five messages of a failure on line 99 of control.lua, something along the lines of "attempt to index a nil value "train" on line 99 of control.lua" -- that might not be an exact quote, and I haven't seen it since it happened so I can't check.

I'm not too familiar with Lua but looking at that code, I wonder if maybe you need to check the existence of a key ('if "train" in p.vehicle') before checking it's value (' if p.vehicle.train '), but I don't know if that's how Lua does it.

**Comment by eblume** [comment]
Ahah! I went back to playing after writing this and hopped in my Gunship from the Airplanes mod and was immediately treated to the error again. I suspect that the mod is messing with `p.vehicle.train` and setting it to a non-indexable value or something. Seems like a bug with that mod and not yours, then. I'll leave it to your judgement.

**Comment by Nexela** [comment]
Are you running the latest version of nanobots? 1.8.6

**Comment by eblume** [comment]
I was not! I was running 1.8.5. I don't seem to see it now that I've updated, but I'll re-open if I do. Thanks for the great mod!
