### ISSUE TITLE
Range bonus from research not being applied

### ISSUE THREAD

**Issue by staviq** [Nexela/Nanobots#59]
I have Nanobot Range 4 researched, but range is actually only about 13x13 tiles.

https://i.imgur.com/6VorE5z.jpg

[aabo5.zip](https://github.com/Nexela/Nanobots/files/1331147/aabo5.zip)

**Comment by Nexela** [comment]
It looks like you manually set the max range of your constructor bots to a lower value, To fix it hold the constructor ammo in your hand and click on the cancel button in the top left corner for the range adjustment.

**Comment by staviq** [comment]
I do not recall changing max range, specifically because i didn't know it was possible until you just told me.
It did however help to increase the range manually just like you said.
