### ISSUE TITLE
Error Loading 1.8.7 update

### ISSUE THREAD

**Issue by DocEternal** [Nexela/Nanobots#62]
@Nexela 

Just installed the newest update thru the mod portal in game. On start it gives the following error:

Error loading mods

Failed to load mods: __Nanobots__/data.lua:2:module stdlib/core not found; no such file __Nanobots__/stdlib/core.lua no such file __Nanobots__/stdlib/core.lua no such file D:?SteamLibrary/steamapps/common/Factorio/data/core/lualib/stdlib/core.lua

Mods to be disabled:
Nanobots

**Comment by chrisgbk** [comment]
The release zip file is missing the stdlib folder; should be able to just pull it from GitHub and insert it.

**Comment by valgarian** [comment]
Yes Thank You! It did the trick.

**Comment by Nexela** [comment]
Sorry, I switched to a junction for stdlib and forgot to update my makefile! Fix incoming
