### ISSUE TITLE
Roboport interface not destroying correctly

### ISSUE THREAD

**Issue by riking** [Nexela/Nanobots#63]
Version: Nanobots 1.8.9

When mining a roboport interface, it left behind the two helper entities.

![image](https://user-images.githubusercontent.com/627891/33577592-5f0036f0-d8f8-11e7-9e20-8149cf7900dd.png)

**Comment by Nexela** [comment]
Looks like I forgot to correctly register an event!   Next version fixes this as well as adds some optimizations around the interface.  Please let me know if you have any issues!

Fixed with  f878382fc46b1e87c55384c8a5fa0174d3f8ce11
