### ISSUE TITLE
Server crash when trying to clean up inventory with SHIFT-C

### ISSUE THREAD

**Issue by Jim-Foster** [Nexela/Nanobots#65]
Thank you for this wonderful mod!  Please let me know if I can help you debug this further. 

39.713 Error MainLoop.cpp:1013: Exception at tick 5089748: Error while running event even-distribution::inventory-cleanup (ID 96)
LuaBurner doesn't contain key fuel_category.
stack traceback:
	__even-distribution__/scripts/cleanup.lua:41: in function 'filterEntities'
	__even-distribution__/scripts/cleanup.lua:25: in function 'func'
	__even-distribution__/control.lua:26: in function <__even-distribution__/control.lua:25>
  39.713 Error ServerMultiplayerManager.cpp:95: MultiplayerManager failed: "Error while running event even-distribution::inventory-cleanup (ID 96)
LuaBurner doesn't contain key fuel_category.
stack traceback:
	__even-distribution__/scripts/cleanup.lua:41: in function 'filterEntities'
	__even-distribution__/scripts/cleanup.lua:25: in function 'func'
	__even-distribution__/control.lua:26: in function <__even-distribution__/control.lua:25>"
  39.713 Info ServerMultiplayerManager.cpp:693: mapTick(5089748) changing state from(InGame) to(Failed)
  39.713 Info GlobalContext.cpp:660: Waiting for child processes to exit:

**Comment by Nexela** [comment]
This looks to be an error with even-distribution mod and not with Nanobots

**Comment by Jim-Foster** [comment]
My apologies, I'm so embarassed. :(  Sorry and thank you again for the
wonderful mod!

**Comment by Nexela** [comment]
No worries I am sure you will find one of my crashes soon!
