### ISSUE TITLE
Nanobots not working when in range of Logistic network.

### ISSUE THREAD

**Issue by staviq** [Nexela/Nanobots#67]
I'm pretty sure they were before the 0.16 update.

[16_2_6.zip](https://github.com/Nexela/Nanobots/files/1570874/16_2_6.zip)
[mod-settings.zip](https://github.com/Nexela/Nanobots/files/1570879/mod-settings.zip)
[mod-list.zip](https://github.com/Nexela/Nanobots/files/1570880/mod-list.zip)

**Comment by Nexela** [comment]
By default nanobots don't work in other networks.  You can either add the
power armor interface or turn off the check in settings

**Comment by staviq** [comment]
Ok, it works once i unchecked this option.

To be honest, the name and the description is wrong, it suggests the exact opposite of what it does.
