### ISSUE TITLE
Nanobots not repairing vehicles.

### ISSUE THREAD

**Issue by staviq** [Nexela/Nanobots#68]
Nanobots are being dispatched, there is this small blue cloud going on, but hp of the vehicles is not going up.

After many "tries" bots randomly start working.

This happens very often.

I have been standing near this locomotive and the car for about 5 minutes now:

https://i.imgur.com/GYUJCGI.jpg

I have seen this problem only happen with vehicles. Trains, cars and tanks.

[16_2_17.zip](https://github.com/Nexela/Nanobots/files/1587793/16_2_17.zip)

[mod-settings.zip](https://github.com/Nexela/Nanobots/files/1587798/mod-settings.zip)

**Comment by staviq** [comment]
Just got the same problem with something other that a vehicle, a chemical plant right next to the player.

[16_2_20.zip](https://github.com/Nexela/Nanobots/files/1592510/16_2_20.zip)

**Comment by Nexela** [comment]
Cannot reproduce, Vehicles are being repaired for me.
