### ISSUE TITLE
Not an issue, not really

### ISSUE THREAD

**Issue by TheVirusWar** [Nexela/Nanobots#70]
Didnt play Factorio for a while, came back to 0.16, the mod on the github is not up to date (thats what my game says), but I saw people play with it? 
Could it be updated or is there somewhere a new page for this mod?

Thanks for making our early lives easier!

**Comment by Nexela** [comment]
Nanobots is updated for .16. Can't remember if I did a release on github
but it is available in the mod portal

**Comment by TheVirusWar** [comment]
Oh well, I guess its time to link my acc with that page...
I like to get my mods off github, it always seemed like it was more up to date than the portal itself, at least to me.
Cheers!
