### ISSUE TITLE
Incompatible with Stormwalls Mod

### ISSUE THREAD

**Issue by InflamedSebi** [Nexela/Nanobots#72]
When building Stormwalls via nanobots there is a non game crashing error and the placed stormwalls do not work. Removing those placed walls by hand will cause a game crashing error. This sound like an issue for Stormwalls, but since it works with normal bots this might just be an incompatibility and maybe u can sort this out.

The error message can be found in the Stormwall topic here:
https://forums.factorio.com/viewtopic.php?f=190&t=57412&start=20#p351111

**Comment by Nexela** [comment]
Should be fixed in one of the latest releases, please reopen if that is not the case.
