### ISSUE TITLE
`on_player_built_tile` is missing `tiles`

### ISSUE THREAD

**Issue by Emilgardis** [Nexela/Nanobots#73]
There is an [error with the latest published release](https://mods.factorio.com/mod/Nanobots/discussion/5abe7e6da79680000937208c) regarding the mod Landfill Painting and any other mod that listens to `on_player_built_tile` and expects an `item` field. This was fixed in 197ed901b on the 0.16.0 branch. There is still a problem however because the event also requires a [`tiles`](http://lua-api.factorio.com/latest/events.html#on_player_built_tile).

I couldn't get the 0.16.0 branch to work and I decided to patch 197ed901b in and added the `tiles` field and that seems to have fixed the problem.

----

(explaining process to make this patch more accessible to users that want this fixed quickly)

Inside `control.lua`, in the `Queue.build_tile_ghost(data)` function change
```lua
create_projectile("nano-projectile-constructors", surface, force, player.position, position)
surface.create_entity {name = "nano-sound-build-tiles", position = position}
script.raise_event(defines.events.on_player_built_tile, {player_index = player.index, positions = {position}})
```
to
```lua
local ptype = data.place_item and game.item_prototypes[data.place_item.name]
create_projectile('nano-projectile-constructors', surface, force, player.position, position)
surface.create_entity {name = 'nano-sound-build-tiles', position = position}
script.raise_event(defines.events.on_player_built_tile, {player_index = player.index, tiles = {{position = position, old_tile = tile}}, item = ptype})
```

**Comment by Nexela** [comment]
No idea why this didn't automatically close. But either way, Should be fixed!  I might release later onz!
