### ISSUE TITLE
New update 2.0.5

### ISSUE THREAD

**Issue by jacenaysh** [Nexela/Nanobots#74]
Playing modded Bob & Angel; updated Nanobots and on restart Bob's Power Mod had an error:

Failed to load mods:__bobpower__/data-updates.lua:8:__boblibrary__/item-functions.lua:47:attempt to compare number with string

Disabled Nanobots and Factorio loaded fine.

**Comment by Nexela** [comment]
This is a problem with boblibrary/bobpower Not sure why the error shows up because of nanobots though.

**Comment by Nexela** [comment]
A bug in bobpower, was angered by a recent stdlib change commited to the wrong branch.
Fixed (mostly) in 18cb9e4d3ae72ca0f8531355b0d3e5d853f384e4

**Comment by jacenaysh** [comment]
Thanks Nexela
