### ISSUE TITLE
2.0.6 broke compatibility with Bob's Power

### ISSUE THREAD

**Issue by goudaonmixer** [Nexela/Nanobots#77]
"Failed to load mods: \_\_bobpower\_\_/data-updates.lua:8: \_\_boblibrary\_\_/item-functions.lua:47: attempt to compare number with string"

![2018-05-12 11_08_40-factorio 0 16 42](https://user-images.githubusercontent.com/28921921/39959827-3852e37e-55dd-11e8-8af4-575b7e586641.png)

Also noted by another user in the [Factorio Mods discussion section](https://mods.factorio.com/mod/Nanobots/discussion/5af710b6677ae80009b0112f).

I don't know much about modding or Lua, but my best guess is that is has to do with this commit: 8f9f8a3b1e7dfa0195a4bfc898c1c144709eecff since it's related to Bob's. 

Reverting to 2.0.2 fixed this for me.

**Comment by Nexela** [comment]
It is related to bobs, I don't know why it worked before and doesn't now. it should have been broken all along.

**Comment by Nexela** [comment]
semi fixed in 18cb9e4d3ae72ca0f8531355b0d3e5d853f384e4
