### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by seludovici** [Nexela/Nanobots#79]
Hi. I got an error while running nanobots and a few other mods. Error code doesn't mean much to me, but I'm pretty sure it says the error was with nanobots. See image. 
![error](https://user-images.githubusercontent.com/41812256/43352917-dd33010a-91f9-11e8-9e88-3cf185cfbcc1.PNG)

**Comment by Alafian** [comment]
I have the same problem, using bob mods and angels mods.

**Comment by Nexela** [comment]
Please re-open this issue with steps to reproduce if it still occurs
