### ISSUE TITLE
nanobots.lua:209: attempt to call field 'inside' (a nil value)

### ISSUE THREAD

**Issue by glouel** [Nexela/Nanobots#85]
First, thanks a lot for this awesome mod, and for updating it to 0.17 so quickly ! Hit a very minor bug that I thought you may want to be aware of. 

Factorio 0.17.2
Nanobots 3.0.0
stdlib 1.0.0

I do get this line in console after putting cutting and pasting some items. Some of those ghost items (some red inserters, some steel furnaces) won't get built by the nanobots (some did), as if these specific items construction is stuck. 

I can paste other items in the same area fine, it looks like nanobots just gave up on these. I can place these manually fine so it's definitely not a blocking issue. And this may not be a nanobots issue considering 0.17 is very new, but thought I'd report none the less. 

I did have a quick look at line 209, looks like it's the scanning for items on the floor that generated the error. I did have a look but don't see any, I tried to grab items on the floor manually in the area but didn't find any. I do remember there was a rock that got destroyed while I cut/pasted my items, so this very well might have been some hickup around that moment. I did try to reproduce a few times but didn't manage. I do have a save available if you want but again, fairly minor issue. 

Thanks a lot for the time you put into this mod.

**Comment by Callindrill** [comment]
This is happening for me every time they try to build very densely packed groups of inserters. They do about every 2nd or 3rd one, and the others remain as ghosts. The mod is still great, but the inserters are why I need it!

**Comment by glouel** [comment]
> Perhaps more alarming is that I think it's still "using" the inserters that it's failing to insert. I can't say for certain, though. Hard to count that many things happening all at once. 

I'm not sure this happens 100% of the time but I can confirm I saw some items disappearing, reproduced it with lights that weren't placed and triggered the error. 

But I've noticed that I get way more items non constructed than the number of errors, my guess is the item is only lost when the error pops in the console, but non constructed items that don't trigger the error may not lose item, that's my rough guess of where things are right now.

Thanks for chiming in @Callindrill !
