### ISSUE TITLE
Nanobots continuously attempt to remove cliffs marked for deletion

### ISSUE THREAD

**Issue by turtlecat8** [Nexela/Nanobots#87]
Nanobots continuously attempt to remove cliffs marked for deletion resulting in consuming charges uselessly.

**Comment by Nexela** [comment]
Hmmmmm should nanobots ignore cliffs or destroy them.....

**Comment by turtlecat8** [comment]
I think normal nanobots should ignore them, because otherwise they would be OP.  But maybe an upgrade  tech that requires cliff explosives to have been researched would make sense.
