### ISSUE TITLE
Dependency flag as incorrect.

### ISSUE THREAD

**Issue by DreamSmith** [Nexela/Nanobots#89]
ModMyFactory shows a dependency oddity
![nano err](https://user-images.githubusercontent.com/6638755/54055873-435d9200-41e6-11e9-9a2c-fed2848086e3.jpg)
with
![nano err2](https://user-images.githubusercontent.com/6638755/54055960-8b7cb480-41e6-11e9-923b-0d81d65c2311.jpg)

**Comment by Nexela** [comment]
Fixed I think
