### ISSUE TITLE
0.17 Upgrade Planner - linear belt upgrades instead of what is in Planner

### ISSUE THREAD

**Issue by notadroid** [Nexela/Nanobots#90]
Not sure if this is one bug or two - 

1 - if I set the upgrade planner in .17 to upgrade yellow belts to blue belts, the nano bots will not do it. the upgrade planner marker gets put down, but no work gets done.
If however, I let the stock factorio bots do the upgrades, the upgrades happens fine. 

2 - using the same upgrade planner (yellow to blue), if I happen to have red belts in my inventory, the nanobots will upgrade the yellow belts to red.

**Comment by Nexela** [comment]
Current api limitation

**Comment by notadroid** [comment]
thanks for the quick reply. my apologies if I missed a note on that somewhere. thanks for making an awesome mod! :) Feel free to close this thread so you can keep track of other more important posts.

**Comment by Nexela** [comment]
Fixed in the latest release!
