### ISSUE TITLE
Crash on 0.17.35 update

### ISSUE THREAD

**Issue by minyan** [Nexela/Nanobots#92]
Tons of error on new / load game:
But it's probably has something to do with stdlib.  
Figured i might as well report the problem here, in case it's also nanobot problem.

**Comment by Xeago** [comment]
@minyan there's a fix at https://github.com/Nexela/Nanobots/pull/93; if you're savvy with installing mods you could install from the zipfile from my fork.

**Comment by minyan** [comment]
Thanks @Xeago , it works; no problem on quick test.

**Comment by Nexela** [comment]
Fixed with #93
