### ISSUE TITLE
Crash on multiplayer startup

### ISSUE THREAD

**Issue by szentigrad3** [Nexela/Nanobots#97]
92.362 Script @__stdlib__/stdlib/core.lua:54: __stdlib__/stdlib/event/changes.lua:114: bad argument #1 to 'pairs' (table expected, got nil)
  92.519 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Nanobots: Early Bots caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Nanobots::on_configuration_changed
__stdlib__/stdlib/event/event.lua:308: __stdlib__/stdlib/event/changes.lua:114: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'error'
        __stdlib__/stdlib/event/event.lua:308: in function 'dispatch_event'
        __stdlib__/stdlib/event/event.lua:372: in function 'dispatch'
        __stdlib__/stdlib/event/event.lua:80: in function <__stdlib__/stdlib/event/event.lua:78>

**Comment by Nexela** [comment]
Should be fixed in the latest STDLIB release
