### ISSUE TITLE
Raise script_raised_revive instead of on_built_entity

### ISSUE THREAD

**Issue by mspielberg** [Nexela/Nanobots#99]
Klonan's Construction Drones uses the `script_raised_revive` event newly added in 0.17, by passing `raise_event = true` to LuaEntity::revive. It would be nice to consolidate on this new event to simplify handling for other mods.

**Comment by Yousei9** [comment]
I'd like to see all system events replaced by script_raised.

Event filtering only works for events raised by Factorio itself. Raising events like on_robot_built_entity in mods won't filter properly and requires all other mods having additional filtering and validity checks in place.

**Comment by Nexela** [comment]
Some thoughts on this.
I do not plan on switching to script_raised in Nanobots.   Mining currently uses player.mine events so for consistency the build events will use on_built events.  (switched to player built in the latest release)
Event filtering was introduced to reduce the overall amount of events you get. Just like checking for .valid you should still check that the event applies to you.
